### ISSUE TITLE
COGID

### ISSUE THREAD

**Issue by thiagochacon** [glottobank/tukano#15]
it looks like the feature "right click COGID" in order to do the alignments sytematically is not working properly in my browser. I've tried it in Firefox and Chrome.

Would that be a local problem? Or a DB problem?

**Comment by LinguList** [comment]
Is this local, that is, only for certain cogids, or global, for all
cases? On my browser it works fine, with firefox and chrome (based on
this link: http://tsv.lingpy.org/?file=tukano)...

**Comment by LinguList** [comment]
BTW: as an alternative, check out DISPLAY -> COGNATE SETS. This opens a
new panel in whcih you can switch through meanings slots with arrows.
Presing on the button on the right, you can also open the alignment.

**Comment by thiagochacon** [comment]
solved. thanks.
